FROM wolframe/rhel5-x64-dev
MAINTAINER abaumann@yahoo.com

RUN yum -y install libicu-devel openssl-devel postgresql84-devel zlib-devel libpng-devel pam-devel cyrus-sasl-devel expect telnet libxslt doxygen docbook-style-xsl
