FROM wolframe/fed20-x64-dev
MAINTAINER abaumann@yahoo.com

RUN yum -y install libicu-devel boost-devel openssl-devel sqlite-devel postgresql-devel libxml2-devel libxslt-devel python3-devel freeimage-devel libharu-devel pam-devel cyrus-sasl-devel doxygen
