FROM wolframe/rhel7-x64-dev
MAINTAINER abaumann@yahoo.com

RUN yum -y install boost-devel openssl-devel sqlite-devel postgresql-devel libxml2-devel libxslt-devel zlib-devel libpng-devel pam-devel cyrus-sasl-devel doxygen
