FROM wolframe/ubuntu1404-x86_64-develop
MAINTAINER abaumann@yahoo.com

RUN apt-get -y --force-yes install libboost-dev libboost-program-options-dev libboost-filesystem-dev libboost-system-dev libboost-regex-dev libboost-thread-dev libboost-locale-dev libssl-dev libsqlite3-dev sqlite3 libpq-dev libxml2-dev libxslt1-dev python3-dev zlib1g-dev libpng12-dev libpam0g-dev libsasl2-dev sasl2-bin expect telnet xsltproc doxygen docbook-xsl lsb-release
