FROM wolframe/centos6-x86_64-develop
MAINTAINER abaumann@yahoo.com

RUN yum -y install libicu-devel openssl-devel sqlite-devel postgresql-devel libxml2-devel libxslt-devel python3-devel zlib-devel libpng-devel pam-devel cyrus-sasl-devel
