FROM wolframe/arch-x64-dev
MAINTAINER abaumann@yahoo.com

RUN pacman --noconfirm -S boost boost-libs openssl sqlite postgresql-libs libxml2 libxslt python zlib libpng pam libsasl expect inetutils doxygen docbook-xsl fop graphviz dia
